### ISSUE TITLE
NCORES in FLASHFMwithFINEMAP

### ISSUE THREAD

**Issue by zouyuxin** [jennasimit/flashfm#2]
Hi,

I'm trying the flashfm package, and there is a bug in `FLASHFMwithFINEMAP` function. The argument `NCORES` is not used in any function in `FLASHFMwithFINEMAP`, so it causes an error in `flashfm`.

**Comment by jennasimit** [comment]
Hello,
Sorry about that - I have now fixed this. The argument NCORES is needed, but the issue was that it was missing from the call of the flashfm function within the FLASHFMwithFINEMAP wrapper. 

Please download and try again.
